name: Branch Name
on:
  pull_request:
    types: [opened]
jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    steps:
      - uses: AlbertHernandez/branch-name-action@v1
        with:
          branch_pattern: 'feature|bugfix'
          comment_for_invalid_branch_name: 'Ups! This branch name is not following the standards!'
          fail_if_invalid_branch_name: 'true'
          ignore_branch_pattern: 'main|develop'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}